/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaRegisterType(0x54ef1694c40a5ef8, typeof(LuaBehaviour))]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8d2f94fa9ba71ed4ab60d2f462582dd0";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader m_PurchaseSound = default;
        [SerializeField] public Highrise.AudioShader m_CaptureSound = default;
        [SerializeField] public Highrise.AudioShader m_PlaceSound = default;
        [SerializeField] public Highrise.AudioShader m_CutSound = default;
        [SerializeField] public Highrise.AudioShader m_FailSound = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_PurchaseSound),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_CaptureSound),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_PlaceSound),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_CutSound),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_FailSound),
            };
        }
    }
}

#endif
