/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BeeEgg")]
    [LuaRegisterType(0x56a22b6ba3feb2a4, typeof(LuaBehaviour))]
    public class BeeEgg : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fc336381194e1b44b96507cadba82a30";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("f6254d22f3043194589f2ea3c2879cca")]
        [SerializeField] public UnityEngine.Object m_Meter = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Meter),
            };
        }
    }
}

#endif
