/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BeeWandererScript")]
    [LuaRegisterType(0x92029be1bafd4e92, typeof(LuaBehaviour))]
    public class BeeWandererScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ba573cce4b0ae8b459bb5c26fb8c671d";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_mainCam = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_mainCam),
            };
        }
    }
}

#endif
