/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BobbingIcon")]
    [LuaRegisterType(0x6ee5764a4d9ee6db, typeof(LuaBehaviour))]
    public class BobbingIcon : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "7c1d69ae4a2824c429a7f11a41e23ab2";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_textString = "";
        [SerializeField] public System.Boolean m_isSmall = false;
        [SerializeField] public System.Boolean m_shouldBob = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_textString),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_isSmall),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_shouldBob),
            };
        }
    }
}

#endif
