/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CreateOrderGui")]
    [LuaRegisterType(0xc924e20bd9eec9da, typeof(LuaBehaviour))]
    public class CreateOrderGui : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "873ec4fa8458de74cbff48f9cd22218e";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_statusObject = default;
        [SerializeField] public UnityEngine.GameObject m_BeeListObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
                CreateSerializedProperty(_script.GetPropertyAt(7), null),
                CreateSerializedProperty(_script.GetPropertyAt(8), null),
                CreateSerializedProperty(_script.GetPropertyAt(9), null),
                CreateSerializedProperty(_script.GetPropertyAt(10), null),
                CreateSerializedProperty(_script.GetPropertyAt(11), null),
                CreateSerializedProperty(_script.GetPropertyAt(12), null),
                CreateSerializedProperty(_script.GetPropertyAt(13), null),
                CreateSerializedProperty(_script.GetPropertyAt(14), null),
                CreateSerializedProperty(_script.GetPropertyAt(15), null),
                CreateSerializedProperty(_script.GetPropertyAt(16), null),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_statusObject),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_BeeListObject),
            };
        }
    }
}

#endif
