/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DailyRewardsWheel")]
    [LuaRegisterType(0xe5f7188c3402b485, typeof(LuaBehaviour))]
    public class DailyRewardsWheel : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ce04bacfb95b47a43ab72950555c6478";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_ItemIcons = default;
        [SerializeField] public UnityEngine.AnimationCurve m_SpinEasing = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_ItemIcons),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_SpinEasing),
            };
        }
    }
}

#endif
