/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EasterEventVariableRetriever")]
    [LuaRegisterType(0xbacd19a9b1e3f90d, typeof(LuaBehaviour))]
    public class EasterEventVariableRetriever : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c8193d2a5dcd548468660386f0bcebdf";
        public override string ScriptGUID => s_scriptGUID;


        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
            };
        }
    }
}

#endif
