/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/EggSpawner")]
    [LuaRegisterType(0xeaea0fc3a63a49b6, typeof(LuaBehaviour))]
    public class EggSpawner : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c5ed8c75affd77340a27356580ade885";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_SpawnLocations = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_RegularEggPrefabs = default;
        [SerializeField] public UnityEngine.GameObject m_PinkEggPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_WhiteEggPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_GoldEggPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SpawnLocations),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_RegularEggPrefabs),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_PinkEggPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_WhiteEggPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_GoldEggPrefab),
            };
        }
    }
}

#endif
