/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FestiveBeeManager")]
    [LuaRegisterType(0xa8da61dd7a2d4e60, typeof(LuaBehaviour))]
    public class FestiveBeeManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "785f28adaf01c93458e226d856b1a49a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_FestiveBee = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_FestiveBee),
            };
        }
    }
}

#endif
