/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Flower")]
    [LuaRegisterType(0x50e5035a65b2eee6, typeof(LuaBehaviour))]
    public class Flower : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2853781996292bb4ba3f6146550ba481";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_id = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_id),
            };
        }
    }
}

#endif
