/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FlowerManager")]
    [LuaRegisterType(0xf2dffed5231892a5, typeof(LuaBehaviour))]
    public class FlowerManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a11b0d0f6b7d4fa48ab14a8a565f7b04";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_SpawnLocations = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_Flowers = default;
        [SerializeField] public UnityEngine.GameObject m_InfoCardObject = default;
        [SerializeField] public UnityEngine.GameObject m_flowerPlaceUi = default;
        [SerializeField] public UnityEngine.GameObject m_statusObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_SpawnLocations),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_Flowers),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_InfoCardObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_flowerPlaceUi),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_statusObject),
            };
        }
    }
}

#endif
