/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/NPCTapHandler")]
    [LuaRegisterType(0x401412ab499db313, typeof(LuaBehaviour))]
    public class NPCTapHandler : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "49f55fd777add68488825bcbc7f83fea";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_npcName = "";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_npcName),
            };
        }
    }
}

#endif
