/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PurchaseHandler")]
    [LuaRegisterType(0x2f195fc2f1799dea, typeof(LuaBehaviour))]
    public class PurchaseHandler : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a805d6cd2ae6f374cac275790437d668";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_InfoCardObject = default;
        [SerializeField] public UnityEngine.GameObject m_statusObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_InfoCardObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_statusObject),
            };
        }
    }
}

#endif
