/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RomanticBeeManager")]
    [LuaRegisterType(0x409ee1dd9e2bee91, typeof(LuaBehaviour))]
    public class RomanticBeeManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "785f28adaf01c93458e226d856b1a49a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_RomanticBee = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_RomanticBee),
            };
        }
    }
}

#endif
