/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaRegisterType(0x4420fd164eed93fa, typeof(LuaBehaviour))]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "33342b1fd4649bd458922bd7fbbf73c3";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_BeeListObject = default;
        [SerializeField] public UnityEngine.GameObject m_InfoCardObject = default;
        [SerializeField] public UnityEngine.GameObject m_PlaceApiaryObject = default;
        [SerializeField] public UnityEngine.GameObject m_CreateOrderGuiObject = default;
        [SerializeField] public UnityEngine.GameObject m_BeestiaryObject = default;
        [SerializeField] public UnityEngine.GameObject m_TutorialObject = default;
        [SerializeField] public UnityEngine.GameObject m_ShearsTutorialObject = default;
        [SerializeField] public UnityEngine.GameObject m_StatsObject = default;
        [SerializeField] public UnityEngine.GameObject m_StatusObject = default;
        [SerializeField] public UnityEngine.GameObject m_PlaceFlowerMenuObject = default;
        [SerializeField] public UnityEngine.GameObject m_AddHatMenuObject = default;
        [SerializeField] public UnityEngine.GameObject m_CenterPlayerButtonObject = default;
        [SerializeField] public UnityEngine.GameObject m_LeaderboardObject = default;
        [SerializeField] public UnityEngine.GameObject m_PlaceFurnitureMenuObject = default;
        [SerializeField] public UnityEngine.GameObject m_PlaceObjectsUiObject = default;
        [SerializeField] public UnityEngine.GameObject m_RemoveFurnitureMenuObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_BeeListObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_InfoCardObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_PlaceApiaryObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_CreateOrderGuiObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_BeestiaryObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_TutorialObject),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_ShearsTutorialObject),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_StatsObject),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_StatusObject),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_PlaceFlowerMenuObject),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_AddHatMenuObject),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_CenterPlayerButtonObject),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_LeaderboardObject),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_PlaceFurnitureMenuObject),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_PlaceObjectsUiObject),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_RemoveFurnitureMenuObject),
            };
        }
    }
}

#endif
